### ISSUE TITLE
Issue with test hanging despite apparent activity on connection

### ISSUE THREAD

**Issue by pontaoski** [MirServer/wlcs#212]
I'm working on implementing a WLCS plugin for KWin, but am running into a pretty big issue up front, where it seems like it should be working, but it's not.

The test hangs on the case `when_creating_second_client_nothing_bad_happens`, seemingly due to the attempt to roundtrip.

AFAIK, doing a roundtrip blocks until all wl_callbacks receive done events, but every wl_callback created by wlcs seems to have a `done` event posted, so I'm not sure what's going on here.

full output (both client and server debug):
```
 ➜ /usr/libexec/wlcs/wlcs ./bin/kwin_wlcs.so 
[==========] Running 1046 tests from 50 test suites.
[----------] Global test environment set-up.
[----------] 12 tests from SelfTest
[ RUN      ] SelfTest.when_creating_second_client_nothing_bad_happens
void KWin::WlcsServer::start() Starting WlcsServer...
void ApplicationThread::run() Starting WlcsServer thread...
WARNING: QApplication was not created in the main() thread.
# this output isn't from wlcs, it's kwin internal stuff
[3375358,698]  -> wl_display@1.get_registry(new id wl_registry@2)
[3375358,891]  -> wl_display@1.sync(new id wl_callback@3)
[3375374,188] wl_display@1.delete_id(3)
[3375374,223] wl_registry@2.global(1, "wl_compositor", 4)
[3375374,248]  -> wl_registry@2.bind(1, "wl_compositor", 3, new id [unknown]@4)
[3375374,282] wl_registry@2.global(2, "zwp_tablet_manager_v2", 1)
[3375374,305]  -> wl_registry@2.bind(2, "zwp_tablet_manager_v2", 1, new id [unknown]@5)
[3375374,344] wl_registry@2.global(3, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[3375374,370] wl_registry@2.global(5, "xdg_wm_base", 3)
[3375374,399] wl_registry@2.global(6, "zwlr_layer_shell_v1", 3)
[3375374,424] wl_registry@2.global(7, "zxdg_decoration_manager_v1", 1)
[3375374,447] wl_registry@2.global(8, "wp_viewporter", 1)
[3375374,469] wl_registry@2.global(9, "wl_shm", 1)
[3375374,493]  -> wl_registry@2.bind(9, "wl_shm", 1, new id [unknown]@6)
[3375374,524] wl_registry@2.global(10, "wl_seat", 7)
[3375374,548]  -> wl_registry@2.bind(10, "wl_seat", 5, new id [unknown]@7)
[3375374,580]  -> zwp_tablet_manager_v2@5.get_tablet_seat(new id zwp_tablet_seat_v2@8, wl_seat@7)
[3375374,601] wl_registry@2.global(11, "zwp_pointer_gestures_v1", 2)
[3375374,623] wl_registry@2.global(12, "zwp_pointer_constraints_v1", 1)
[3375374,646] wl_registry@2.global(13, "wl_data_device_manager", 3)
[3375374,669]  -> wl_registry@2.bind(13, "wl_data_device_manager", 1, new id [unknown]@9)
[3375374,700]  -> wl_data_device_manager@9.get_data_device(new id wl_data_device@10, wl_seat@7)
[3375374,722] wl_registry@2.global(14, "zwlr_data_control_manager_v1", 2)
[3375374,746] wl_registry@2.global(15, "zwp_primary_selection_device_manager_v1", 1)
[3375374,771]  -> wl_registry@2.bind(15, "zwp_primary_selection_device_manager_v1", 1, new id [unknown]@11)
[3375374,806]  -> zwp_primary_selection_device_manager_v1@11.get_device(new id zwp_primary_selection_device_v1@12, wl_seat@7)
[3375374,830] wl_registry@2.global(16, "org_kde_kwin_idle", 1)
[3375374,855] wl_registry@2.global(17, "zwp_idle_inhibit_manager_v1", 1)
[3375374,878] wl_registry@2.global(18, "org_kde_plasma_shell", 6)
[3375374,901] wl_registry@2.global(19, "org_kde_kwin_appmenu_manager", 1)
[3375374,924] wl_registry@2.global(20, "org_kde_kwin_server_decoration_palette_manager", 1)
[3375374,950] wl_registry@2.global(22, "org_kde_plasma_virtual_desktop_management", 2)
[3375374,974] wl_registry@2.global(24, "org_kde_kwin_shadow_manager", 2)
[3375374,996] wl_registry@2.global(25, "org_kde_kwin_dpms_manager", 1)
[3375375,019] wl_registry@2.global(26, "org_kde_kwin_server_decoration_manager", 1)
[3375375,064] wl_registry@2.global(27, "kde_output_management_v2", 1)
[3375375,087] wl_registry@2.global(28, "zxdg_output_manager_v1", 3)
[3375375,150]  -> wl_registry@2.bind(28, "zxdg_output_manager_v1", 3, new id [unknown]@13)
[3375375,182]  -> wl_display@1.sync(new id wl_callback@14)
[3375375,197] wl_registry@2.global(29, "wl_subcompositor", 1)
[3375375,223]  -> wl_registry@2.bind(29, "wl_subcompositor", 1, new id [unknown]@15)
[3375375,260] wl_registry@2.global(30, "zxdg_exporter_v2", 1)
[3375375,285] wl_registry@2.global(31, "zxdg_importer_v2", 1)
[3375375,311] wl_registry@2.global(34, "xdg_activation_v1", 1)
[3375375,336] wl_registry@2.global(35, "zwp_relative_pointer_manager_v1", 1)
[3375375,367] wl_registry@2.global(37, "wl_drm", 2)
[3375375,392] wl_registry@2.global(38, "zwp_linux_dmabuf_v1", 3)
[3375375,410] wl_registry@2.global(39, "kde_output_device_v2", 1)
[3375375,429] wl_registry@2.global(40, "wl_output", 3)
[3375375,454]  -> wl_registry@2.bind(40, "wl_output", 2, new id [unknown]@16)
[3375375,489]  -> zxdg_output_manager_v1@13.get_xdg_output(new id zxdg_output_v1@17, wl_output@16)
[3375375,508] wl_registry@2.global(41, "kde_output_device_v2", 1)
[3375375,534] wl_registry@2.global(42, "wl_output", 3)
[3375375,560]  -> wl_registry@2.bind(42, "wl_output", 2, new id [unknown]@18)
[3375375,596]  -> zxdg_output_manager_v1@13.get_xdg_output(new id zxdg_output_v1@19, wl_output@18)
[3375375,625] wl_registry@2.global(44, "zwp_text_input_manager_v2", 1)
[3375375,651]  -> wl_registry@2.bind(44, "zwp_text_input_manager_v2", 1, new id [unknown]@20)
[3375375,691]  -> zwp_text_input_manager_v2@20.get_text_input(new id zwp_text_input_v2@21, wl_seat@7)
[3375375,715] wl_registry@2.global(45, "zwp_text_input_manager_v3", 1)
[3375375,741] wl_registry@2.global(46, "org_kde_kwin_blur_manager", 1)
[3375375,766] wl_registry@2.global(47, "org_kde_kwin_contrast_manager", 1)
[3375375,792] wl_registry@2.global(48, "org_kde_kwin_slide_manager", 1)
[3375375,817] wl_callback@3.done(100964)
[3375376,974] wl_display@1.delete_id(14)
[3375376,994] wl_shm@6.format(0)
[3375377,006] wl_shm@6.format(1)
[3375377,017] wl_shm@6.format(808669761)
[3375377,029] wl_shm@6.format(808669784)
[3375377,039] wl_shm@6.format(808665665)
[3375377,050] wl_shm@6.format(808665688)
[3375377,060] wl_seat@7.capabilities(3)
[3375377,077]  -> wl_seat@7.get_keyboard(new id wl_keyboard@3)
[3375377,095]  -> wl_seat@7.get_pointer(new id wl_pointer@22)
[3375377,115] wl_seat@7.name("")
[3375377,126] wl_callback@14.done(100964)
[3375377,140] wl_output@16.mode(1, 1920, 1080, 60000)
[3375377,172] wl_output@16.scale(1)
[3375377,186] wl_output@16.geometry(1280, 0, 530, 300, 0, "Dell Inc.", "DELL SE2416H/9DRWM867235B", 0)
[3375377,229] wl_output@16.done()
[3375377,236] zxdg_output_v1@17.logical_position(1280, 0)
[3375377,248] zxdg_output_v1@17.logical_size(1920, 1080)
[3375377,259] zxdg_output_v1@17.name("HDMI-A-1")
[3375377,268] zxdg_output_v1@17.description("Dell Inc. DELL SE2416H/9DRWM867235B")
[3375377,277] wl_output@16.done()
[3375377,299] wl_output@18.mode(1, 1280, 1024, 60020)
[3375377,320] wl_output@18.scale(1)
[3375377,328] wl_output@18.geometry(0, 56, 340, 270, 0, "Dell Inc.", "DELL 1704FPV/H630456GA4JR", 0)
[3375377,361] wl_output@18.done()
[3375377,368] zxdg_output_v1@19.logical_position(0, 56)
[3375377,385] zxdg_output_v1@19.logical_size(1280, 1024)
[3375377,398] zxdg_output_v1@19.name("DVI-D-1")
[3375377,406] zxdg_output_v1@19.description("Dell Inc. DELL 1704FPV/H630456GA4JR")
[3375377,414] wl_output@18.done()
[3375386,623]  -> wl_display@1.get_registry(new id wl_registry@14)
[3375386,647]  -> wl_display@1.sync(new id wl_callback@23)
QFile::remove: Empty or null file name
void ApplicationThread::run() Initting Wayland Server...
void ApplicationThread::run() Setting up output size...
void ApplicationThread::run() Setting up virtual outputs
void ApplicationThread::run() Starting KWin App...
performing startup...
init platform...
create color manager...
createry internal connection...
QObject::connect(QAbstractEventDispatcher, KWayland::Client::ConnectionThread): invalid nullptr parameter
kf.globalaccel.kglobalacceld: Failed to register service org.kde.kglobalaccel
void ApplicationThread::run() Waiting On Started...
[3375456,682]  -> wl_display@1.get_registry(new id wl_registry@2)
[3375456,722]  -> wl_display@1.sync(new id wl_callback@3)
starting wayland server...
QObject::connect(QAbstractEventDispatcher, KWaylandServer::FilteredDisplay): invalid nullptr parameter
finalizing startup...
[3375767,041] wl_display@1.delete_id(23)
[3375767,070] wl_keyboard@3.repeat_info(25, 600)
[3375767,082] wl_keyboard@3.keymap(1, fd 24, 64027)
[3375769,504] wl_registry@14.global(1, "wl_compositor", 4)
[3375769,533] wl_registry@14.global(2, "zwp_tablet_manager_v2", 1)
[3375769,552] wl_registry@14.global(3, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[3375769,568] wl_registry@14.global(5, "xdg_wm_base", 3)
[3375769,585] wl_registry@14.global(6, "zwlr_layer_shell_v1", 3)
[3375769,602] wl_registry@14.global(7, "zxdg_decoration_manager_v1", 1)
[3375769,620] wl_registry@14.global(8, "wp_viewporter", 1)
[3375769,638] wl_registry@14.global(9, "wl_shm", 1)
[3375769,656] wl_registry@14.global(10, "wl_seat", 7)
[3375769,670] wl_registry@14.global(11, "zwp_pointer_gestures_v1", 2)
[3375769,686] wl_registry@14.global(12, "zwp_pointer_constraints_v1", 1)
[3375769,703] wl_registry@14.global(13, "wl_data_device_manager", 3)
[3375769,719] wl_registry@14.global(14, "zwlr_data_control_manager_v1", 2)
[3375769,737] wl_registry@14.global(15, "zwp_primary_selection_device_manager_v1", 1)
[3375769,756] wl_registry@14.global(16, "org_kde_kwin_idle", 1)
[3375769,773] wl_registry@14.global(17, "zwp_idle_inhibit_manager_v1", 1)
[3375769,792] wl_registry@14.global(18, "org_kde_plasma_shell", 6)
[3375769,809] wl_registry@14.global(19, "org_kde_kwin_appmenu_manager", 1)
[3375769,825] wl_registry@14.global(20, "org_kde_kwin_server_decoration_palette_manager", 1)
[3375769,842] wl_registry@14.global(22, "org_kde_plasma_virtual_desktop_management", 2)
[3375769,862] wl_registry@14.global(24, "org_kde_kwin_shadow_manager", 2)
[3375769,884] wl_registry@14.global(25, "org_kde_kwin_dpms_manager", 1)
[3375769,904] wl_registry@14.global(26, "org_kde_kwin_server_decoration_manager", 1)
[3375769,921] wl_registry@14.global(27, "kde_output_management_v2", 1)
[3375769,940] wl_registry@14.global(28, "zxdg_output_manager_v1", 3)
[3375769,959] wl_registry@14.global(29, "wl_subcompositor", 1)
[3375769,977] wl_registry@14.global(30, "zxdg_exporter_v2", 1)
[3375769,996] wl_registry@14.global(31, "zxdg_importer_v2", 1)
[3375770,013] wl_registry@14.global(34, "xdg_activation_v1", 1)
[3375770,030] wl_registry@14.global(35, "zwp_relative_pointer_manager_v1", 1)
[3375770,048] wl_registry@14.global(37, "wl_drm", 2)
[3375770,066] wl_registry@14.global(38, "zwp_linux_dmabuf_v1", 3)
[3375770,085] wl_registry@14.global(39, "kde_output_device_v2", 1)
[3375770,102] wl_registry@14.global(40, "wl_output", 3)
[3375770,125] wl_registry@14.global(41, "kde_output_device_v2", 1)
[3375770,143] wl_registry@14.global(42, "wl_output", 3)
[3375770,161] wl_registry@14.global(44, "zwp_text_input_manager_v2", 1)
[3375770,180] wl_registry@14.global(45, "zwp_text_input_manager_v3", 1)
[3375770,199] wl_registry@14.global(46, "org_kde_kwin_blur_manager", 1)
[3375770,216] wl_registry@14.global(47, "org_kde_kwin_contrast_manager", 1)
[3375770,234] wl_registry@14.global(48, "org_kde_kwin_slide_manager", 1)
[3375770,252] wl_callback@23.done(100964)
[3375770,295]  -> wl_registry@14.bind(19, "org_kde_kwin_appmenu_manager", 1, new id [unknown]@24)
void ApplicationThread::run() Started!
void ApplicationThread::run() Sanity checking outputs...
void ApplicationThread::run() Initialising Workspace...
[3378824,967] wl_output@16.done()
[3378825,004] wl_output@18.done()
void ApplicationThread::run() Thread initialisation done, starting event loop...
void KWin::WlcsServer::start() Started WlcsServer...
int KWin::WlcsServer::createClientSocket() Creating socket connection...
QObject: Cannot create children for a parent that is in a different thread.
(Parent is KWaylandServer::FilteredDisplay(0x7fc7480460c0), parent's thread is QThread(0x7fc748000de0), current thread is QThread(0x55f0fa1f4fd0)
int KWin::WlcsServer::createClientSocket() Returning socket connection...
# this is when output starts to be from wlcs
[3381081,896]  -> wl_display@1.get_registry(new id wl_registry@2)
[3381081,927]  -> wl_display@1.sync(new id wl_callback@3)
event dispatch!
[3381083,253] wl_display@1.get_registry(new id wl_registry@2)
[3381083,271]  -> wl_registry@2.global(1, "wl_compositor", 4)
[3381083,286]  -> wl_registry@2.global(2, "zwp_tablet_manager_v2", 1)
[3381083,303]  -> wl_registry@2.global(3, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[3381083,316]  -> wl_registry@2.global(4, "zwp_input_panel_v1", 1)
[3381083,331]  -> wl_registry@2.global(5, "xdg_wm_base", 3)
[3381083,346]  -> wl_registry@2.global(6, "zwlr_layer_shell_v1", 3)
[3381083,359]  -> wl_registry@2.global(7, "zxdg_decoration_manager_v1", 1)
[3381083,372]  -> wl_registry@2.global(8, "wp_viewporter", 1)
[3381083,386]  -> wl_registry@2.global(9, "wl_shm", 1)
[3381083,403]  -> wl_registry@2.global(10, "wl_seat", 7)
[3381083,421]  -> wl_registry@2.global(11, "zwp_pointer_gestures_v1", 2)
[3381083,439]  -> wl_registry@2.global(12, "zwp_pointer_constraints_v1", 1)
[3381083,452]  -> wl_registry@2.global(13, "wl_data_device_manager", 3)
[3381083,464]  -> wl_registry@2.global(14, "zwlr_data_control_manager_v1", 2)
[3381083,481]  -> wl_registry@2.global(15, "zwp_primary_selection_device_manager_v1", 1)
[3381083,514]  -> wl_registry@2.global(16, "org_kde_kwin_idle", 1)
[3381083,528]  -> wl_registry@2.global(17, "zwp_idle_inhibit_manager_v1", 1)
[3381083,541]  -> wl_registry@2.global(18, "org_kde_plasma_shell", 6)
[3381083,553]  -> wl_registry@2.global(19, "org_kde_kwin_appmenu_manager", 1)
[3381083,581]  -> wl_registry@2.global(20, "org_kde_kwin_server_decoration_palette_manager", 1)
[3381083,602]  -> wl_registry@2.global(21, "org_kde_plasma_window_management", 14)
[3381083,619]  -> wl_registry@2.global(22, "org_kde_plasma_virtual_desktop_management", 2)
[3381083,637]  -> wl_registry@2.global(23, "org_kde_plasma_activation_feedback", 1)
[3381083,654]  -> wl_registry@2.global(24, "org_kde_kwin_shadow_manager", 2)
[3381083,670]  -> wl_registry@2.global(25, "org_kde_kwin_dpms_manager", 1)
[3381083,688]  -> wl_registry@2.global(26, "org_kde_kwin_server_decoration_manager", 1)
[3381083,705]  -> wl_registry@2.global(27, "kde_output_management_v2", 1)
[3381083,721]  -> wl_registry@2.global(28, "zxdg_output_manager_v1", 3)
[3381083,739]  -> wl_registry@2.global(29, "wl_subcompositor", 1)
[3381083,757]  -> wl_registry@2.global(30, "zxdg_exporter_v2", 1)
[3381083,775]  -> wl_registry@2.global(31, "zxdg_importer_v2", 1)
[3381083,793]  -> wl_registry@2.global(32, "org_kde_kwin_keystate", 1)
[3381083,811]  -> wl_registry@2.global(33, "zwp_input_method_v1", 1)
[3381083,827]  -> wl_registry@2.global(34, "xdg_activation_v1", 1)
[3381083,844]  -> wl_registry@2.global(35, "kde_output_device_v2", 1)
[3381083,862]  -> wl_registry@2.global(36, "kde_output_device_v2", 1)
[3381083,881]  -> wl_registry@2.global(37, "wl_output", 3)
[3381083,898]  -> wl_registry@2.global(38, "wl_output", 3)
[3381083,915]  -> wl_registry@2.global(39, "org_kde_kwin_fake_input", 4)
[3381083,933] wl_display@1.sync(new id wl_callback@3)
[3381083,944]  -> wl_callback@3.done(0)
[3381083,953]  -> wl_display@1.delete_id(3)
[3384324,211] wl_output@16.done()
[3384324,247] wl_output@18.done()
[3389826,038] wl_output@16.done()
[3389826,074] wl_output@18.done()
```

**Comment by wmww** [comment]
The logs are kinda a mess because of WAYLAND_DEBUG=1 doesn't handle multiple connections well (see https://github.com/wmww/wayland-debug/issues/5). It does look like there are 6 `wl_callback.sync` requests and only 4 `wl_callback.done` events, that that could very well be your problem.

If you can get https://github.com/wmww/wayland-debug working in GDB mode with it that will make it a lot easier to understand what's going on, as that *can* track multiple connections at once without getting confused.

**Comment by pontaoski** [comment]
i was wondering how i invoke that with WLCS, since i'm not sure how to run a program with args other than using the gdb command line to configure that

how i tried doing it:
```
➜ ./main.py -g
Running subprocess: ['gdb', '-ex', 'python import sys; sys.argv = ["./main.py"]; exec(open("./main.py").read())']
GNU gdb (GDB) Fedora 10.2-1.fc34
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) file /usr/libexec/wlcs/wlcs
Load new symbol table from "/usr/libexec/wlcs/wlcs"? (y or n) y
Reading symbols from /usr/libexec/wlcs/wlcs...
Load new symbol table from "/usr/lib/debug/usr/libexec/wlcs/wlcs-1.3.0-1.fc34.x86_64.debug"? (y or n) y
Reading symbols from /usr/lib/debug/usr/libexec/wlcs/wlcs-1.3.0-1.fc34.x86_64.debug...
(gdb) set args /home/jpontaoski/kde/build/kwin/bin/kwin_wlcs.so
(gdb) r
Starting program: /usr/libexec/wlcs/wlcs /home/jpontaoski/kde/build/kwin/bin/kwin_wlcs.so
warning: Expected absolute pathname for libpthread in the inferior, but got .gnu_debugdata for /lib64/libpthread.so.0.
warning: File "/usr/lib64/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/lib/golang/src/runtime/runtime-gdb.py".
To enable execution of this file add
        add-auto-load-safe-path /usr/lib64/libthread_db-1.0.so
line to your configuration file "/home/jpontaoski/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "/home/jpontaoski/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
[==========] Running 1046 tests from 50 test suites.
[----------] Global test environment set-up.
[----------] 12 tests from SelfTest
[ RUN      ] SelfTest.when_creating_second_client_nothing_bad_happens
void KWin::WlcsServer::start() Starting WlcsServer...
[New LWP 1642704]
void ApplicationThread::run() Starting WlcsServer thread...
WARNING: QApplication was not created in the main() thread.
Traceback (most recent call last):
  File "/home/jpontaoski/Code/GitHub/wayland-debug/backends/gdb_plugin/plugin.py", line 71, in stop
    connection_id, message = self.message_extractor()
  File "/home/jpontaoski/Code/GitHub/wayland-debug/backends/gdb_plugin/extract.py", line 150, in sent_message
    connection = frame.read_var('connection')
ValueError: Variable 'connection' not found.
[Switching to LWP 1642704]

Thread 2 "wlcs" hit Breakpoint -4, wl_closure_send (connection=0x7fffe800b8a0, closure=0x7fffe8001070) at ../src/connection.c:1218
1218            size = serialize_closure(closure, buffer, buffer_size);
Missing separate debuginfos, use: dnf debuginfo-install bzip2-libs-1.0.8-6.fc34.x86_64 dbus-libs-1.12.20-3.fc34.x86_64 double-conversion-3.1.5-4.fc34.x86_64 fontconfig-2.13.93-6.fc34.x86_64 freetype-2.10.4-3.fc34.x86_64 glib2-2.68.2-1.fc34.x86_64 glibc-2.33-14.fc34.x86_64 gmock-1.10.0-6.fc34.x86_64 graphite2-1.3.14-7.fc34.x86_64 harfbuzz-2.7.4-3.fc34.x86_64 keyutils-libs-1.6.1-2.fc34.x86_64 lcms2-2.12-1.fc34.x86_64 libICE-1.0.10-6.fc34.x86_64 libXau-1.0.9-6.fc34.x86_64 libXext-1.3.4-6.fc34.x86_64 libXfixes-5.0.3-14.fc34.x86_64 libXtst-1.2.3-14.fc34.x86_64 libblkid-2.36.2-1.fc34.x86_64 libbrotli-1.0.9-4.fc34.x86_64 libcanberra-0.30-24.fc34.x86_64 libcom_err-1.45.6-5.fc34.x86_64 libepoxy-1.5.8-1.fc34.x86_64 libevdev-1.11.0-1.fc34.x86_64 libffi-3.1-28.fc34.x86_64 libgcc-11.2.1-1.fc34.x86_64 libgcrypt-1.9.3-2.fc34.x86_64 libglvnd-1.3.3-1.fc34.x86_64 libglvnd-egl-1.3.3-1.fc34.x86_64 libglvnd-glx-1.3.3-1.fc34.x86_64 libicu-67.1-6.fc34.x86_64 libinput-1.18.0-1.fc34.x86_64 libmount-2.36.2-1.fc34.x86_64 libpng-1.6.37-10.fc34.x86_64 libselinux-3.2-1.fc34.x86_64 libstdc++-11.2.1-1.fc34.x86_64 libtdb-1.4.3-6.fc34.x86_64 libtool-ltdl-2.4.6-40.fc34.x86_64 libusbmuxd-2.0.2-4.fc34.x86_64 libuuid-2.36.2-1.fc34.x86_64 libvorbis-1.3.7-3.fc34.x86_64 libxcb-1.13.1-7.fc34.x86_64 libxkbcommon-1.3.0-1.fc34.x86_64 libxml2-2.9.12-4.fc34.x86_64 libzstd-1.5.0-1.fc34.x86_64 lz4-libs-1.9.3-2.fc34.x86_64 mtdev-1.1.5-20.fc34.x86_64 openssl-libs-1.1.1k-1.fc34.x86_64 pcre-8.44-3.fc34.1.x86_64 pcre2-10.36-4.fc34.x86_64 pcre2-utf16-10.36-4.fc34.x86_64 systemd-libs-248.3-1.fc34.x86_64 xcb-util-keysyms-0.4.0-15.fc34.x86_64
(gdb) cont
Continuing.
Traceback (most recent call last):
  File "/home/jpontaoski/Code/GitHub/wayland-debug/backends/gdb_plugin/plugin.py", line 71, in stop
    connection_id, message = self.message_extractor()
  File "/home/jpontaoski/Code/GitHub/wayland-debug/backends/gdb_plugin/extract.py", line 150, in sent_message
    connection = frame.read_var('connection')
ValueError: Variable 'connection' not found.

Thread 2 "wlcs" hit Breakpoint -4, wl_closure_send (connection=0x7fffe800b8a0, closure=0x7fffe8001070) at ../src/connection.c:1218
1218            size = serialize_closure(closure, buffer, buffer_size);
(gdb) cont
Continuing.
Traceback (most recent call last):
  File "/home/jpontaoski/Code/GitHub/wayland-debug/backends/gdb_plugin/plugin.py", line 71, in stop
    connection_id, message = self.message_extractor()
  File "/home/jpontaoski/Code/GitHub/wayland-debug/backends/gdb_plugin/extract.py", line 127, in received_message
    connection = _fast_access(wl_display, 'wl_display.connection')
  File "/home/jpontaoski/Code/GitHub/wayland-debug/backends/gdb_plugin/extract.py", line 43, in _fast_access
    return (value.cast(gdb_char_ptr_type) + offset).cast(ret_type_ptr_ptr).dereference()
gdb.error: Invalid cast.

Thread 2 "wlcs" hit Breakpoint -2, wl_closure_invoke (closure=closure@entry=0x7fffe80071c0, target=target@entry=0x7fffe8007bf0, opcode=opcode@entry=1, data=0x7fffe8007bf0, flags=<optimized out>)
    at ../src/connection.c:991
991     wl_closure_invoke(struct wl_closure *closure, uint32_t flags,
(gdb) 
```

as you can see, it's not working very well

**Comment by wmww** [comment]
Oh, right, so everything that comes after the `-g` is sent to gdb, so you can invoke it like so:
```
./main.py -g --args /usr/libexec/wlcs/wlcs /home/jpontaoski/kde/build/kwin/bin/kwin_wlcs.so
```

Perhaps I should give an example of this (there's a lot of usability stuff in `wayland-debug` that could do with some improving)

I'm not sure if this will fix your problem or not

**Comment by pontaoski** [comment]
```
 ➜ ./main.py -g --args /usr/libexec/wlcs/wlcs /home/jpontaoski/kde/build/kwin/bin/kwin_wlcs.so
Running subprocess: ['gdb', '-ex', 'python import sys; sys.argv = ["./main.py"]; exec(open("./main.py").read())', '--args', '/usr/libexec/wlcs/wlcs', '/home/jpontaoski/kde/build/kwin/bin/kwin_wlcs.so']
GNU gdb (GDB) Fedora 10.2-1.fc34
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/libexec/wlcs/wlcs...
Reading symbols from /usr/lib/debug/usr/libexec/wlcs/wlcs-1.3.0-1.fc34.x86_64.debug...
(gdb) r
Starting program: /usr/libexec/wlcs/wlcs /home/jpontaoski/kde/build/kwin/bin/kwin_wlcs.so
warning: Expected absolute pathname for libpthread in the inferior, but got .gnu_debugdata for /lib64/libpthread.so.0.
warning: File "/usr/lib64/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/lib/golang/src/runtime/runtime-gdb.py".
To enable execution of this file add
        add-auto-load-safe-path /usr/lib64/libthread_db-1.0.so
line to your configuration file "/home/jpontaoski/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "/home/jpontaoski/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
[==========] Running 1046 tests from 50 test suites.
[----------] Global test environment set-up.
[----------] 12 tests from SelfTest
[ RUN      ] SelfTest.when_creating_second_client_nothing_bad_happens
void KWin::WlcsServer::start() Starting WlcsServer...
[New LWP 1645348]
void ApplicationThread::run() Starting WlcsServer thread...
WARNING: QApplication was not created in the main() thread.
Traceback (most recent call last):
  File "/home/jpontaoski/Code/GitHub/wayland-debug/backends/gdb_plugin/plugin.py", line 71, in stop
    connection_id, message = self.message_extractor()
  File "/home/jpontaoski/Code/GitHub/wayland-debug/backends/gdb_plugin/extract.py", line 150, in sent_message
    connection = frame.read_var('connection')
ValueError: Variable 'connection' not found.
[Switching to LWP 1645348]

Thread 2 "wlcs" hit Breakpoint -4, wl_closure_send (connection=0x7fffe800b8a0, closure=0x7fffe8001070) at ../src/connection.c:1218
1218            size = serialize_closure(closure, buffer, buffer_size);
Missing separate debuginfos, use: dnf debuginfo-install bzip2-libs-1.0.8-6.fc34.x86_64 dbus-libs-1.12.20-3.fc34.x86_64 double-conversion-3.1.5-4.fc34.x86_64 fontconfig-2.13.93-6.fc34.x86_64 freetype-2.10.4-3.fc34.x86_64 glib2-2.68.2-1.fc34.x86_64 glibc-2.33-14.fc34.x86_64 gmock-1.10.0-6.fc34.x86_64 graphite2-1.3.14-7.fc34.x86_64 harfbuzz-2.7.4-3.fc34.x86_64 keyutils-libs-1.6.1-2.fc34.x86_64 lcms2-2.12-1.fc34.x86_64 libICE-1.0.10-6.fc34.x86_64 libXau-1.0.9-6.fc34.x86_64 libXext-1.3.4-6.fc34.x86_64 libXfixes-5.0.3-14.fc34.x86_64 libXtst-1.2.3-14.fc34.x86_64 libblkid-2.36.2-1.fc34.x86_64 libbrotli-1.0.9-4.fc34.x86_64 libcanberra-0.30-24.fc34.x86_64 libcom_err-1.45.6-5.fc34.x86_64 libepoxy-1.5.8-1.fc34.x86_64 libevdev-1.11.0-1.fc34.x86_64 libffi-3.1-28.fc34.x86_64 libgcc-11.2.1-1.fc34.x86_64 libgcrypt-1.9.3-2.fc34.x86_64 libglvnd-1.3.3-1.fc34.x86_64 libglvnd-egl-1.3.3-1.fc34.x86_64 libglvnd-glx-1.3.3-1.fc34.x86_64 libicu-67.1-6.fc34.x86_64 libinput-1.18.0-1.fc34.x86_64 libmount-2.36.2-1.fc34.x86_64 libpng-1.6.37-10.fc34.x86_64 libselinux-3.2-1.fc34.x86_64 libstdc++-11.2.1-1.fc34.x86_64 libtdb-1.4.3-6.fc34.x86_64 libtool-ltdl-2.4.6-40.fc34.x86_64 libusbmuxd-2.0.2-4.fc34.x86_64 libuuid-2.36.2-1.fc34.x86_64 libvorbis-1.3.7-3.fc34.x86_64 libxcb-1.13.1-7.fc34.x86_64 libxkbcommon-1.3.0-1.fc34.x86_64 libxml2-2.9.12-4.fc34.x86_64 libzstd-1.5.0-1.fc34.x86_64 lz4-libs-1.9.3-2.fc34.x86_64 mtdev-1.1.5-20.fc34.x86_64 openssl-libs-1.1.1k-1.fc34.x86_64 pcre-8.44-3.fc34.1.x86_64 pcre2-10.36-4.fc34.x86_64 pcre2-utf16-10.36-4.fc34.x86_64 systemd-libs-248.3-1.fc34.x86_64 xcb-util-keysyms-0.4.0-15.fc34.x86_64
(gdb) 
```
hm

**Comment by wmww** [comment]
Hmm, all I can think of is either you don't have libwayland debug symbols (although it should detect that), or your libwayland is built differently optimised and gdb isn't able to pull the information wayland-debug needs. You could try building `libwayland-client.so` and `libwayland-server.so` from source and make wlcs use them with `LD_PRELOAD` (or just try to solve the problem without wayland-debug).

I have an idea to make a wayland-debug snap that ships it's own libwayland to prevents these problems, but unfortunately I haven't gotten that off the ground.
